import codecs
import pickle
from typing import Dict, List, Union

from wbb import db

"""
SOME THINGS ARE FUCKED UP HERE, LIKE TOGGLEABLES HAVE THEIR OWN COLLECTION
(SHOULD FIX IT WITH SOMETHING LIKE TOGGLEDB, BUT I WON'T, AS IT WILL TAKE
TOO MUCH TIME AND WILL BE BAD FOR ALREADY STORED DATA)
"""

